{
  "formatVersion": "1.1",
  "component": {
    "group": "org.graalvm.buildtools",
    "module": "native-gradle-plugin",
    "version": "0.9.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "native-gradle-plugin-0.9.7.1.jar",
          "url": "native-gradle-plugin-0.9.7.1.jar",
          "size": 55009,
          "sha512": "229a4f450fc2e77a8044ec8bbdc7e993fddce0408f3c19e4428ca27cc4af967522c24bc7b31c7855b354045d450609fe43a9fa5f2c337ba386060f59fb5020cd",
          "sha256": "ecabc6576f4008170f22a14c6fb6b04c2c3137ab0bfaf39f08294c49442d40f1",
          "sha1": "502f0d0dc010eb96632e46032ba073979befbc5f",
          "md5": "49ccc1a7816adebc8c0be016fa67a59d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.graalvm.buildtools",
          "module": "utils",
          "version": {
            "requires": "0.9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "native-gradle-plugin-0.9.7.1.jar",
          "url": "native-gradle-plugin-0.9.7.1.jar",
          "size": 55009,
          "sha512": "229a4f450fc2e77a8044ec8bbdc7e993fddce0408f3c19e4428ca27cc4af967522c24bc7b31c7855b354045d450609fe43a9fa5f2c337ba386060f59fb5020cd",
          "sha256": "ecabc6576f4008170f22a14c6fb6b04c2c3137ab0bfaf39f08294c49442d40f1",
          "sha1": "502f0d0dc010eb96632e46032ba073979befbc5f",
          "md5": "49ccc1a7816adebc8c0be016fa67a59d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-gradle-plugin-0.9.7.1-javadoc.jar",
          "url": "native-gradle-plugin-0.9.7.1-javadoc.jar",
          "size": 486944,
          "sha512": "cee84f2c45d40ffed8cc73d4fe558d93a8bd126e18ca96ddcd044efe929ad9c83fff9e2989b020b45f2a5ea35467144a7d56e4016cd1eb73965ec18c15f34ed3",
          "sha256": "ddfe233fc8dd9356afc853ec1e809eb0a9d9ccd8d23c629a41427c108f229da9",
          "sha1": "8ecaee2bf2ab3e265927b7c2b587c68ce77a33d2",
          "md5": "3e2c24659f7fbfb5d66a164b1e128f6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-gradle-plugin-0.9.7.1-sources.jar",
          "url": "native-gradle-plugin-0.9.7.1-sources.jar",
          "size": 47195,
          "sha512": "e9776d712e0320618e2ed94f4dc3bfeb7cb12752729a568b13a037b984394980e44eaab745f066c11ba5b49427077727f7f6d76b1f266f741911cafa3adfb89f",
          "sha256": "0f4cca0d0fdb70446d01cd7adbd80d4ee36655bc1112c7552ff92f0b13b09693",
          "sha1": "a5879ebec50f3afe5bd3aed7a66cfa9781f8772e",
          "md5": "a161d1b88d3370083e23d8fe18398bec"
        }
      ]
    }
  ]
}
